name = "lwe"
main = "./src/index.js"
routes = [
  "lwe.rethinkdns.com/*",
  "lwe.bravedns.com/*"
]
usage_model = "bundled"
workers_dev = true
compatibility_date = "2022-06-21"

[vars]


##################
#-----SECRETS----#
##################
# for documentation purposes only
# developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler
# [secrets]
# LWE_SECRET_KEY_HMAC_A = ""
# LWE_SECRET_KEY_HKDF_A = ""